document.addEventListener('DOMContentLoaded', () => {
    const faqContainer = document.getElementById('faq-container');

    // Fetch data from data.json generated by the Chat UX
    fetch('data.json')
        .then(response => {
            if (!response.ok) {
                throw new Error('Network response was not ok');
            }
            return response.json();
        })
        .then(data => {
            renderFAQs(data);
        })
        .catch(error => {
            console.error('Error fetching FAQs:', error);
            faqContainer.innerHTML = '<p style="text-align:center; color: #ef4444; font-size: 1.2rem; padding: 2rem;">Error loading data. Make sure you are running a local web server (Stage 3)!</p>';
        });

    function renderFAQs(faqs) {
        faqs.forEach((faq, index) => {
            const item = document.createElement('div');
            item.classList.add('faq-item');
            
            // Unique IDs for accessibility
            const buttonId = `faq-button-${index}`;
            const contentId = `faq-content-${index}`;

            item.innerHTML = `
                <button class="faq-question" id="${buttonId}" aria-expanded="false" aria-controls="${contentId}">
                    <span>${faq.question}</span>
                    <span class="faq-icon"></span>
                </button>
                <div class="faq-answer-wrapper" id="${contentId}" aria-hidden="true">
                    <div class="faq-answer">
                        ${faq.answer}
                    </div>
                </div>
            `;

            faqContainer.appendChild(item);

            const button = item.querySelector('.faq-question');
            const wrapper = item.querySelector('.faq-answer-wrapper');

            button.addEventListener('click', () => {
                const isActive = item.classList.contains('active');
                
                // Close all other FAQs to keep it clean
                document.querySelectorAll('.faq-item.active').forEach(activeItem => {
                    activeItem.classList.remove('active');
                    const activeBtn = activeItem.querySelector('.faq-question');
                    const activeWrapper = activeItem.querySelector('.faq-answer-wrapper');
                    activeBtn.setAttribute('aria-expanded', 'false');
                    activeWrapper.setAttribute('aria-hidden', 'true');
                    activeWrapper.style.maxHeight = null;
                });

                if (!isActive) {
                    // Open the clicked one
                    item.classList.add('active');
                    button.setAttribute('aria-expanded', 'true');
                    wrapper.setAttribute('aria-hidden', 'false');
                    // Calculate and set the scroll height for smooth CSS transition
                    wrapper.style.maxHeight = wrapper.scrollHeight + "px";
                }
            });
        });
    }
});
